### ISSUE TITLE
Ruby: Line breaks fire and skip next prompt

### ISSUE THREAD

**Issue by ryanbrookepayne** [ryanbrookepayne/weekly-report#5]
When I enter multiline text, it fires and skips the next command. See attached screenshot.

![weekly-report-multi-line-bug_ruby](https://user-images.githubusercontent.com/12212345/47941941-29214980-debe-11e8-936d-75d1b01c735a.jpg)

Can we escape input with line breaks?

**Comment by ryanbrookepayne** [comment]
@brandonbaker40 This issue is happening on Ruby and Shell. Can you take a look at the Ruby version? I'll grab the [shell issue](https://github.com/ryanbrookepayne/weekly-report/issues/6)?

**Comment by brandonbaker40** [comment]
Yea, I'll work on it this weekend. I dabbled with it a little bit last
week. Any progress on the shell script?

--Brandon

**Comment by ryanbrookepayne** [comment]
@brandonbaker40 I did look into the shell issue. I'm not sure it's actually resolvable. I don't think you can paste multi-line text into a terminal. Give it another look. But if you can't find the solution, close this issue.

**Comment by ryanbrookepayne** [comment]
This is no longer worth resolving.
